Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - db/migrate/*
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
    - config/environments/development.rb

Rails/Output:
  Exclude:
    - db/seeds.rb
